workflows:
  android-workflow-id:
    name: Android ToDo's App Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        GITHUB_TOKEN
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      tag_patterns:                
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Debug App with Flutter
        script: |
          flutter build apk --debug
      - name: Show Build apk Folder
        script: |
          ls build/app/outputs/flutter-apk
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - bagusmertasntn@gmail.com
      scripts:
        - name: Check for apk
          script: |
            apkPath=$(find build -name "*.apk" | head -1)
            if [[ -z ${apkPath} ]]; then
              echo "No .apk files were found"
            else
              echo "Publishing .apk artifacts"
            fi
      scripts: 
        - name: Publish to Github
          script: |
            if [ -z ${CM_TAG} ]; then
              echo "Not a tag build will not publish GitHub release"
              exit 0
            fi 
            
          gh release create "${CM_TAG}" \
              --title "<ToDos> ${CM_TAG}" \
              --notes-file changelog.md \
              build/app/outputs/flutter-apk/*.apk
              
